/*
* Class Type        : Constants Container
* Created by        : Amritesh
* Description       : To define all the Constants and reuseable methods to be used by other Classes.
**/

public class Constants {
    
    public static final string FFE_DONOR_DONOR                  = System.label.FFE_Donor_Donor;
    public static final string FFE_DONOR_ALMUNI                 = System.label.FFE_Donor_Alumni;
    public static final string FFE_DONOR_FACILITAtOR            = System.label.FFE_Donor_Facilitator;
    public static final string FFE_DONOR_STUDENT                = System.label.FFE_Donor_Student;
    public static final string FFE_Mentor                       = System.label.FFE_Mentor;
    public static final string EMAIL_TEMPLATE_NAME              = System.label.Email_Template_Name;
    public static final string CONTACT_SOBJECT                  = System.label.Contact_Sobject;
    public static final string DONOR_SCHOLAR_COURSETYPE         = System.label.Donor_Scholar_CourseType;
    public static final string DONOR_RESIDENTIAL_STATUS         = System.label.Donor_Residential_Status;
    public static final string SCHOLAR_GENDER                   = System.label.Scholar_Gender;
    public static final string ERROR_MSG                        = System.label.Error_Msg;
    public static final string SUCCESS_MSG                      = System.label.Success_Msg;
    public static final string MAPPING_SUCCESS_MSG              = System.label.Mapping_Success_Msg;
    public static final string AWAITING_FUND_STATUS             = System.label.Awaiting_Fund_Status;
    public static final string AWAITING_FUND_STATUS_API         = System.label.Awaiting_Fund_Status_API;
    public static final string CITIZENSHIP_NON_INDIAN           = System.label.Citizenship_Non_Indian;
    public static final string CITIZENSHIP_INDIAN               = System.label.Citizenship_Indian;
    public static final string FFE_NAME                         = System.label.FFE_Name;
    public static final string DONOR_TEMPORARY_URL_TEMPLATE     = System.label.Donor_Temporary_URL_Template;
    public static final string NO_USER_FOUND                    = System.label.No_User_Found;
    public static final string TEMP_URL_SENT_CONFIRMATION       = System.Label.temporary_url_sent_confirmation;
    public static final string SUCCESS_REGISTERED_MSG           = System.Label.Success_Registered_Msg;
    public static final string EMAIL_DUPLICATE_ERR_MSG          = System.Label.Email_Duplicate_Err_Msg;
    public static final string PHONE_DUPLICATE_ERR_MSG          = System.Label.Phone_Duplicate_Err_Msg;
    public static final string MOBILE_DUPLICATE_ERR_MSG         = System.Label.Mobile_Duplicate_Err_Msg;
    public static final string COLLEGEMASTER_SOBJECT            = System.Label.CollegeMaster_Sobject;
    public static final string COLLEGEMASTER_STUDENTCLZRATING   = System.Label.CollegeMaster_StudentClzrating;
    public static final string STUDENT_COURSE                   = System.Label.Student_Course;
    public static final string STUDENT_BANK_ACCOUNT_TYPE        = System.Label.Student_BankAccountType; 
    public static final Double MAX_INCOME_RANGE                 = Double.ValueOf(System.label.Max_Family_Income_Range);
    public static final string ERROR_MESSAGE                    = System.Label.Error_Message;
    public static final string ACTIVE_APPLICATION               = System.Label.Active_Application;  
    public static final string APPROVED_STATUS                  = System.Label.Approved_Status;
    public static final string AMOUNT_FUNDED                    = System.Label.Amount_Funded;
    public static final string APP_STAGE_CLOSED                 = System.Label.App_Stage_Closed;
    public static final string SCHOLARSHIP_APPLICATION_DN      = System.Label.Scholarship_Application_DN;
    public static final string SCHOLARSHIP_RENEWAL_APPLICATION_DN = System.Label.Scholarship_Renewal_Application_DN;
    public static final string SCHOLARSHIP_APPLICATION          = System.Label.Scholarship_Application;
    public static final string SCHOLARSHIP_RENEWAL_APPLICATION  = System.Label.Scholarship_Renewal_Application;
    public static final string ADDITIONAL_APPLICATION           = System.Label.Additional_Application;
    public static final string ALL_AWAITING_STUDENT             = System.Label.All_Awaiting_Student;
    public static final string ALL_MULTI_DONOR_MAPPED_STUDENT             = 'All Multi Donor Mapped Student';
    public static final string ALL_MAPPED_STUDENT               = System.Label.All_Mapped_Student;
    public static final string ALL_UNMAPPED_STUDENT             = System.Label.All_UnMapped_Student;
    Public static final String DISBURMENT_SUCCESS               = System.Label.Disburment_Success;
    public static final string POSTED_STAGE                     = System.Label.Posted_Stage;
    public static final string IT_CERTIFICATE_TEMPLATE          = System.label.It_Certificate_Template;
    public static final string MAIL_SENT_SUCCESS_MSG            = System.label.Mail_Sent_Success_Msg;
    public static final string SCHOLAR_BRANCH_FIELD             = System.label.Scholar_Branch_Field;   
    public static final string ACADEMIC_TYPE                    = System.label.Academic_Type;
    public static final string OCCUPATION_TYPE                  = System.label.Occupation_Type;
    public static final string SIBILINGNO                  = System.label.SIBILINGNO;
    public static final string ACCOMODATION_TYPE                = System.label.Accomodation_Type;
    public static final string YEAR_STUDING_IN                  = System.label.Year_Studying_In;
    public static final string APPLICATION_SOBJECT              = System.label.Application_Sobject;
    public static final string APP_STAGE_OPEN                   = System.label.App_Stage_Open;
    public static final string PRELIM_SUCCESS_MSG               = System.label.Prelim_form_submission_message;
    public static final string SELECTED_APPLICATION             = System.label.Selected_Application;
    public static final string FACILITATORMAPPING_SUCCESSMSG    = System.label.FacilitatorMapping_SuccessMsg;
    public static final string ONLINE_MATCHED_APPLICATION       = System.label.Online_Matched_Application;
    public static final string INPROGRESS_APPLICATION           = System.label.InProgress_Application;
    public static final string APPLICATIONTYPE_NEW              = System.label.ApplicationType_New;
    public static final string APPLICATIONTYPE_RENEWAL          = System.label.ApplicationType_Renewal;
    public static final string STUDENTPROFILE_UPDATEMSG         = System.label.Studentprofile_Updatemsg;
    public static final string VERIFIED_BY_FAC                  = System.label.Verified_By_Fac;
    public static final string REJECTED_BY_FAC                  = System.label.Rejected_By_Fac;
    public static final string ONLINE_WORKINGMODE               = System.label.Online_WorkingMode;
    public static final string OFFLINE_WORKINGMODE              = System.label.Offline_WorkingMode;
    public static final string STUDENT_PROFILE_PIC              = System.label.Student_Profile_Pic;
    public static final string GRADING_SYSTEM_FIELD_API      = System.label.Grading_System_Field_Api;
    public static final string RENEWAL_APPLN_SUCCESS_MSG    = System.label.Renewal_Appln_Success_Msg;
    public static final string EXISTNG_APPLN_ERR_MSG      = System.label.Existing_Appln_Err_Msg;
    public static final string STUDENT_COUNTRY          = System.label.Student_Country;
    public static final string OTHER_STRING            = System.label.Other_String;
    public static final string FACILITATOR_INPUT_MSG      = System.label.Facilitator_Input_Msg;
    public static final string TEMPORARY_LOGIN_TEMPLATE      = System.label.Temporary_Login_Template;
    public static final string VERIFIED_BY_FACILITATOR      = System.label.Verified_By_Facilitator;
    public static final string REJECTED_BY_FACILITATOR      = System.label.Rejected_By_Facilitator;
    public static final string APPLICATION_APPROVAL_NAME    = System.label.Application_Approval_Name;
  public static final string DOCUMENT_UPLOADED        = System.label.Document_Uploaded; 
    public static final string APPLICATION_SUCESS_MSG      = System.label.Application_Sucess_msg; 
    
    //TriggerContextVariable
    public static boolean APPLICATION_TRIGGER_RUNNING           = false;
    public static boolean Contact_TRIGGER_RUNNING             = false;
    public static boolean SMS_TRIGGER_RUNNING                   = false;
    public static final string APP_EXTERNAL_STATUS              = System.label.App_External_Status; 
    
    public static final string DONOR_CATEGORY                = System.label.Donor_Category;
    public static final string PENDING_APPROVAL                 = System.Label.Pending_Approval;
    public static final String COMPLETION_FLAG_NO               = System.label.CompletionFlag_No;
    public static final String COMPLETION_FLAG_YES              = System.label.CompletionFlag_Yes;
    public static final Integer MILESTONE_VALUE_2         = Integer.valueOf(System.label.MilestoneValue2);
    public static final Integer MILESTONE_VALUE_3         = Integer.valueOf(System.label.MilestoneValue3);
    public static final String THIRD_YEAR_PART_1                = System.label.THIRD_YEAR_PART_1;
    public static final String THIRD_YEAR_PART_2                = System.label.THIRD_YEAR_PART_2;
    public static final String THIRD_YEAR              = System.label.THIRD_YEAR;
    public static final String NOT_PROCESSED          = System.label.Not_Processed;
    public static final String PROCESSED              = System.label.Processed;
    public static final String INELIGIBLE                       = System.label.Ineligible;
    public static final String ELIGIBLE                         = System.label.Eligible;
    public static final String BE_BTECH                         = System.label.BE_B_Tech;
    public static final string INTEGRATED_MTECH                 = system.label.INTEGRATED_MTECH;
    public static final String COMPLETED                        = System.label.Completed;
    public static final String ONGOING                          = System.label.Ongoing;
    public static final String FUNDED                           = System.label.Funded;
    public static final String FIRST_YEAR                       = System.label.X1st_Year;
    public static final String Aadhar_Err_Msg                   = System.label.Aadhar_Err_Msg;
    public static final String DocumentUploadingMessage         = System.label.DocumnetUploadMessage;
    public static final String Facilitator_error                = System.label.Facilitator_Error;
    //Contents to SMS
    public static final String when_Student_register_for_sholarship_text      = System.label.When_Student_register_for_scholarship;
    public static final String When_scholarship_application_gets_selected_text   = System.label.When_scholarship_application_gets_selected;
    public static final String When_scholarship_application_gets_Approved_text   = System.label.When_scholarship_application_gets_Approved;
    public static final String When_facilitator_assigned_to_Student_text        = System.label.When_facilitator_assigned_to_Student;
    public static final String Document_missing_notification_text           = System.label.Document_missing_notification;
    public static final String On_transfer_of_Scholarship_to_Student_text      = System.label.On_transfer_of_Scholarship_to_Student;
    public static final String On_new_Donor_Registration_text                   = System.label.On_new_Donor_Registration;
    public static final String X80G_certificate_text                             = System.label.X80G_certificate;
    public static final String Welcome_Mail_to_Facilitator_text                  = System.label.Welcome_Mail_to_Facilitator;
    public static final String Student_s_Assigned_text                           = System.label.Student_s_Assigned;
    public static final String On_transfer_of_Scholarship_to_Students_text       = System.label.On_transfer_of_Scholarship_to_Students;
    
    public static final String Disbursed                                  = System.label.Disbursed; 
    public static final String Scholarship_Transferred                    = System.label.Scholarship_Transferred;
    
    public static final String Email_to_facilitator_after_Scholarship_is_Transferred_to_Student = System.Label.Email_to_facilitator_after_Scholarship_is_Transferred_to_Student;
    public static final String Email_to_Student_after_Scholarship_Transferred_to_Account        = System.Label.Email_to_Student_after_Scholarship_Transferred_to_Account;
    public static final String FFE_Facilitator                                           = System.label.FFE_Facilitator;
    public static final String FFE_Account                                             = System.label.FFE_Account;
    public static final String Fund_Transfer_error_message                             = System.label.Fund_Transfer_error_message;
    //training 
    public static final String Aptitude                                     = System.label.Aptitude;
    public static final String English                                      = System.label.English;
    public static final String All                                          = System.label.All;
    public static final String Training_internal_status                     = System.label.Training_internal_status;
    public static final String zero_amount_balance_error_message            = System.label.zero_amount_balance_error_message;
    public static final String Amount_Entry_as_Zero                         = System.label.Amount_Entry_as_Zero;
    
    //alumini to donor batch uses
    public static final String MBBS                                 = System.label.MBBS;
    public static final String IntegratedMtech                             = System.label.IntegratedMtech;
    public static final String BEBTech                                 = System.label.BEBTech;
    public static final String fourthYear                               = System.label.fourthYear;
    public static final String fifthYear                               = System.label.fifthYear;
    public static final String MdeFinalYEar                               = System.label.MdeFinalYEar;
    public static final String AluminiToDonor                             = System.label.AluminiToDonor;
    //Alumni to donor site uses
    public static final String PAN_Duplicate_Error_message                  = System.label.PAN_Duplicate_Error_message;

  public static final string COUNTRY_IND                  = System.label.Country_India;
    public static final string COUNTRY_US                  = System.label.Country_US;
    public static final string googleFacebookDuplicate_Email                = System.label.googleFacebookDuplicate_Email;
    public static final string Email_Updation_Message                       = System.label.Email_Updation_Message;
    
    //Email for Contributors uses
    public static final string Email_Scheduled_Msg                          = System.label.Email_Scheduled_Msg;
    
    //Refund amount uses
    public static final string Refunded                                = System.label.Refunded;
    public static final string Refund_received                            = System.label.Refund_received;
    //Transfer fund
    public static final string FCRA_Duplicate_Err_Msg                    = System.label.FCRA_Duplicate_Err_Msg;
    //new donor registered through Quick donation uses
    //public static final string NewDonorRegiteredThroughtQuickDonationPage   = System.Label.NewDonorRegiteredThroughtQuickDonationPage;
  //to stop sms on ready for disbursment
    public static boolean Stop_SMS                                     = false;
    
    //2018
    public static final string Aadhaar_error_message_donorRegstr_page     = system.label.Aadhaar_error_message_donorRegstr_page;
    
    //These variable are introduce to send email only once in a transaction from code -- Sumit Gaurav 09-June-2020
    public static boolean Email_sent_to_Student_Facilitator_after_disbursement = false;
    public static boolean Email_sent_to_Student_On_Facilitator_Matched = false;
    public static boolean EightyG_Reciept_sent_to_Donor = false;
    
    
    // These variables are introduced with respect to Mentorship portal
    public static string MENTOR_MENTEE_SITE_URL = System.label.Mentorship_Site_URL;
    
}