/*
* Purpose: Test class for DN_OnDeletionofDonorStudentMapping Class
*/

// This piece of code is not required after the new process= "Donor Application Mapping".
@isTest
public class DN_OnDeletionofDonorStudentMapping_Test {
    
   /* public static testmethod void checkOnDeletionofDSMtrigger(){
        
        test.startTest();
        User auser = Utility_Test.createUser('ZXYSpoo099@gmail.com');
        System.runAs(auser){
            Contact student = Utility_Test.insertNewStudentRec('abc','sss',null,null,null,null,null,0,0,null,null);
            insert student;
            Contact donor   = Utility_Test.insertNewDonorId('abc','xyz');
            insert donor;
            Donor_Student_Mapping__c dsm = Utility_Test.insertNewDonorStudentMapping(student,donor);
            insert dsm;
            delete dsm;
        }
        test.stopTest();
    }*/
}