/*
Purpose     : Constants values used for Donation Service Class
CreatedDate	: 13/02/2017
Author		:Amritesh
*/
public class DN_ServiceConstants {
	
    public static final string ENGINEERING_PROGRAM			= System.label.Engineering_Program;
    public static final string MEDICAL_PROGRAM				= System.label.Medical_Program;
    public static final string SCHEDULE_TYPE_DIVIDE			= System.label.Schedule_Type_Divide;
    public static final string SCHEDULE_TYPE_MULTIPLY		= System.label.Schedule_Type_Multiply;
    public static final string DONATION_FAILED_ERROR_MSG	= system.label.Donation_Failed_Message;
    public static final string FIRST_OF_RECDONATION_STRING	= System.label.First_Of_Recdonation_String;
    public static final string PLEDGED_DONATION				= System.label.Pledged_Donation;
    public static final string DONATION_RECORDTYPE			= System.label.Donation_RecordType;
    public static final string DN_ORDER_KEY					= System.label.Dn_Order_Key;
    public static final string CONCATENATION_VALUE			= System.label.Concatenation_Value;
    public static final string HASH_FUNCTION_ALOGORITHM		= System.label.Hash_Function_Algorithm;
    public static final string ENCRYPTION_ALOGORITHM		= System.label.Encryption_Algorithm;
	public static final string ONE_TIME_PAYMENT				= System.label.One_Time_Payment;
	public static final string RECURRING_PAYMENT			= System.label.Recurring_Payment;
	public static final string USD_CURRENCY					= System.label.Usd_Currency;
	public static final string INR_CURRENCY					= System.label.Inr_Currency;
    public static final string ORDER_PARAM					= System.label.Order_Param;
    public static final string CURRENCY_PARAM				= System.label.Currency_Param;
    public static final string AMOUNT_PARAM					= System.label.Amount_Param;
    public static final string SYSTEM_ERROR					= System.label.System_Error;
    Public static final string RECURRING_DONATION			= System.label.Recurring_Donation;
    Public static final string GENERAL_DONATION				= System.label.General_Donation;
    Public static final string PAYMENT_SUCCESS				= System.label.Payment_Success;
    Public static final string PAYMENT_FAILED				= System.label.Payment_Failed;
    Public static final string PAYMENT_CANCEL				= System.label.Payment_Aborted;
    Public static final string DONOR_INFO_UPDATED			= System.label.Donor_Info_Updated;
    Public static final string PAYMENT_DELETE				= System.label.Payment_Delete;
    Public static final decimal DEFAULT_USD_COVERSION_RATE	= 65.00;  
}